version: '3'

services:
  chatbot:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - PORT=5000
    volumes:
      - ./data:/app/data
      - ./models:/app/models